# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: sudo apt-get install git-crypt
  displayName: 'apt-get install git-crypt'
- script: wget ${keyLocation}
  displayName: 'download BcatBotFramework key'
- script: cd ./BcatBotFramework && git-crypt unlock ../BcatBotFramework.key && cd ..
  displayName: 'unlock BcatBotFramework'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
